/**
 * N8c (2026-07-09): GOAP — Goal-Oriented Action Planning, made deterministic.
 *
 * This is the dump's ONE concrete, correct, non-drone core idea, reformulated for a CODING AGENT
 * instead of a drone: the LLM/stochastic advisor picks the GOAL; a symbolic planner searches the
 * state space and executes. The advisor NEVER touches actuators (here: the filesystem / deploy /
 * branch state) — it only names an intent. This is ADR-003 made executable and is the literal
 * "Constraint Satisfaction / symbolic planner" the dump describes.
 *
 * Anti-hallucination property (the dump's whole point): a goal with an unsatisfied precondition
 * yields NO PATH — the kernel physically cannot act on a hallucinated plan, because every action
 * and every transition is enumerated in Rust, not generated by the model.
 *
 * Deterministic: A* over a finite state graph. No RNG, no SGD, no Date. Falsifiable RED+GREEN.
 *
 * FLAG-OFF: this module is inert unless a caller builds a WorldState + actions and calls `plan`.
 */

export type WorldState = Record<string, string | number | boolean>;

export interface GoapAction<S extends WorldState = WorldState> {
  name: string;
  /** Preconditions: every key must match (deep-equal) for the action to be applicable. */
  pre: Partial<S>;
  /** Effects: applied to the world after the action (overwrites matched keys). */
  eff: Partial<S>;
  /** Cost for A* (lower = preferred). Must be > 0. */
  cost: number;
  /**
   * Optional hard safety invariant: even if preconditions pass, the action is REFUSED if this
   * returns false (e.g. "never deploy with a dirty branch"). This is the symbolic firewall —
   * the kernel's Safe State, checked BEFORE execution, not after.
   */
  invariant?: (s: S) => boolean;
}

function matches<S extends WorldState>(world: S, want: Partial<S>): boolean {
  for (const k of Object.keys(want)) {
    if (world[k] !== (want as Record<string, unknown>)[k]) return false;
  }
  return true;
}

function apply<S extends WorldState>(world: S, eff: Partial<S>): S {
  return { ...world, ...eff };
}

export interface PlanResult<S extends WorldState = WorldState> {
  ok: boolean;
  /** ordered action names from current state to goal (empty when already at goal / unreachable). */
  plan: string[];
  /** terminal world reached (equals goal when ok; last reached otherwise). */
  world: S;
  /** why a plan failed (for self-correction feedback to the advisor). */
  reason?: 'already-satisfied' | 'unreachable' | 'invariant-violated';
}

/**
 * A* over the state space. State key = JSON of the world (deterministic). Returns the cheapest
 * action sequence reaching `goal`, or ok:false with a reason. Bounded by `maxExpansions` so a
 * goal with no path cannot hang (deterministic termination, no infinite search).
 */
export function plan<S extends WorldState>(
  start: S,
  goal: Partial<S>,
  actions: GoapAction<S>[],
  opts: { maxExpansions?: number; heuristic?: (s: S) => number } = {},
): PlanResult<S> {
  const maxExp = opts.maxExpansions ?? 2000;
  const h = opts.heuristic ?? ((s: S) => Object.keys(goal).filter((k) => s[k] !== (goal as Record<string, unknown>)[k]).length);
  if (matches(start, goal)) return { ok: true, plan: [], world: start, reason: 'already-satisfied' };

  // A* frontier: [fScore, worldKey, world, path]
  const startKey = JSON.stringify(start);
  const open: Array<{ f: number; key: string; world: S; path: string[] }> = [
    { f: h(start), key: startKey, world: start, path: [] },
  ];
  const bestG = new Map<string, number>([[startKey, 0]]);
  let expansions = 0;

  while (open.length) {
    // pop lowest f (linear scan — state spaces here are small; deterministic)
    let bi = 0;
    for (let i = 1; i < open.length; i++) if (open[i].f < open[bi].f) bi = i;
    const cur = open.splice(bi, 1)[0];
    if (matches(cur.world, goal)) return { ok: true, plan: cur.path, world: cur.world };
    if (++expansions > maxExp) break;

    for (const a of actions) {
      if (!matches(cur.world, a.pre)) continue;
      if (a.invariant && !a.invariant(cur.world)) continue; // symbolic firewall
      const next = apply(cur.world, a.eff);
      const nKey = JSON.stringify(next);
      const g = bestG.get(cur.key)! + a.cost;
      if (bestG.has(nKey) && bestG.get(nKey)! <= g) continue;
      bestG.set(nKey, g);
      open.push({ f: g + h(next), key: nKey, world: next, path: [...cur.path, a.name] });
    }
  }
  return { ok: false, plan: [], world: start, reason: 'unreachable' };
}

/**
 * Hard-invariant refusal (the dump's "kernel rejects the hallucination"): run a proposed action
 * against the world and return whether the symbolic firewall blocks it. Pure — used by callers
 * who want to PRE-CHECK an advisor's intent before committing to a full search.
 */
export function actionAllowed<S extends WorldState>(world: S, a: GoapAction<S>): boolean {
  if (!matches(world, a.pre)) return false;
  if (a.invariant && !a.invariant(world)) return false;
  return true;
}
