// rust-core/examples/cheby_coeff_inner.rs
// Runs the eqc-generated, self-asserting proof for the Chebyshev-coefficient inner term
// used by `spectral_propagate` in src/lib.rs. Exit non-zero iff the hand-derived formula
// diverges from the SymPy source of truth at the sampled points.
//
//   cargo run --example cheby_coeff_inner
//
// The proof body is GENERATED by tools/eqc (SymPy) — do not edit by hand; regenerate:
//   python3 tools/eqc/eqc.py --expr '2*exp(-0.5*b*coeff*t - 0.5*b*coeff*t*cos(theta))*cos(k*theta)/qp' \
//           --args b coeff t k theta qp --proof
include!("../eqc-proofs/cheby_coeff_inner.rs");
