// GENERATED by eqc — self-asserting proof for `cheby_coeff_inner`.
// exit 0 ⟺ the emitted f64 (and fixed-point) code matches the SymPy reference.
/// GENERATED by eqc from: cheby_coeff_inner = 2*exp(-0.5*b*coeff*t*cos(theta) - 0.5*b*coeff*t)*cos(k*theta)/qp
/// f64 variant — dynamics path (not bitwise-deterministic across targets on libm calls).
#[inline(always)]
pub fn cheby_coeff_inner_f64(b: f64, coeff: f64, t: f64, k: f64, theta: f64, qp: f64) -> f64 {
    2.0*(-0.5*b*coeff*t - 0.5*b*coeff*t*theta.cos()).exp()*(k*theta).cos()*qp.recip()
}

fn main() {
    let got = cheby_coeff_inner_f64(2.0f64, 0.5f64, 1.0f64, 3.0f64, 0.7f64, 64.0f64);
    assert!((got - (-0.006527974053609924f64)).abs() < 0.000000001f64, "f64 sample 0: got {} want -0.006527974053609924", got);
    let got = cheby_coeff_inner_f64(4.0f64, 0.1f64, 0.3f64, 0.0f64, 1.2f64, 64.0f64);
    assert!((got - (0.028797192821449814f64)).abs() < 0.000000001f64, "f64 sample 1: got {} want 0.028797192821449814", got);
    let got = cheby_coeff_inner_f64(1.0f64, 1.0f64, 2.0f64, 7.0f64, 2.5f64, 64.0f64);
    assert!((got - (0.005620869637645259f64)).abs() < 0.000000001f64, "f64 sample 2: got {} want 0.005620869637645259", got);
    let got = cheby_coeff_inner_f64(3.0f64, 0.3f64, 0.8f64, 5.0f64, 0.2f64, 64.0f64);
    assert!((got - (0.008277731337292158f64)).abs() < 0.000000001f64, "f64 sample 3: got {} want 0.008277731337292158", got);
    let got = cheby_coeff_inner_f64(2.5f64, 0.7f64, 1.5f64, 2.0f64, 2.9f64, 64.0f64);
    assert!((got - (0.026637531674752708f64)).abs() < 0.000000001f64, "f64 sample 4: got {} want 0.026637531674752708", got);
    println!("eqc proof OK: cheby_coeff_inner (5 samples, fixed=False)");
}


// GENERATION NOTE: source expr MUST be the EXPANDED form
//   exp(-0.5*b*coeff*t - 0.5*b*coeff*t*cos(theta)) * cos(k*theta) * 2/qp
// NOT exp(-coeff*t*(b/2)*(1+cos(theta))) — sympy's rust_code printer mis-distributes
//   coeff*(cos+1), emitting '+ 1.0' instead of the scaled constant (codegen bug).
