/// GENERATED by eqc from: cheby_recur_weight = 2/b
/// f64 variant — dynamics path (not bitwise-deterministic across targets on libm calls).
#[inline(always)]
pub fn cheby_recur_weight_f64(b: f64) -> f64 {
    2.0*b.recip()
}