// GENERATED by eqc — self-asserting proof for `cheby_recur_weight`.
// exit 0 ⟺ the emitted f64 (and fixed-point) code matches the SymPy reference.
/// GENERATED by eqc from: cheby_recur_weight = 2/b
/// f64 variant — dynamics path (not bitwise-deterministic across targets on libm calls).
#[inline(always)]
pub fn cheby_recur_weight_f64(b: f64) -> f64 {
    2.0*b.recip()
}

fn main() {
    let got = cheby_recur_weight_f64(2.0f64);
    assert!((got - (1.0f64)).abs() < 0.000000000001f64, "f64 sample 0: got {} want 1.0", got);
    let got = cheby_recur_weight_f64(4.0f64);
    assert!((got - (0.5f64)).abs() < 0.000000000001f64, "f64 sample 1: got {} want 0.5", got);
    let got = cheby_recur_weight_f64(1.5f64);
    assert!((got - (1.3333333333333333f64)).abs() < 0.000000000001f64, "f64 sample 2: got {} want 1.3333333333333333", got);
    let got = cheby_recur_weight_f64(8.0f64);
    assert!((got - (0.25f64)).abs() < 0.000000000001f64, "f64 sample 3: got {} want 0.25", got);
    println!("eqc proof OK: cheby_recur_weight (4 samples, fixed=False)");
}
