// GENERATED by eqc — self-asserting proof for `cosine_div`.
// exit 0 ⟺ the emitted f64 (and fixed-point) code matches the SymPy reference.
/// GENERATED by eqc from: cosine_div = dot/sqrt(na*nb)
/// f64 variant — dynamics path (not bitwise-deterministic across targets on libm calls).
#[inline(always)]
pub fn cosine_div_f64(dot: f64, na: f64, nb: f64) -> f64 {
    dot*(na*nb).sqrt().recip()
}

fn main() {
    let got = cosine_div_f64(0.0f64, 1.0f64, 1.0f64);
    assert!((got - (0.0f64)).abs() < 0.000000000001f64, "f64 sample 0: got {} want 0.0", got);
    let got = cosine_div_f64(25.0f64, 25.0f64, 25.0f64);
    assert!((got - (1.0f64)).abs() < 0.000000000001f64, "f64 sample 1: got {} want 1.0", got);
    let got = cosine_div_f64(4.0f64, 5.0f64, 5.0f64);
    assert!((got - (0.8f64)).abs() < 0.000000000001f64, "f64 sample 2: got {} want 0.8", got);
    let got = cosine_div_f64(0.0f64, 13.0f64, 13.0f64);
    assert!((got - (0.0f64)).abs() < 0.000000000001f64, "f64 sample 3: got {} want 0.0", got);
    println!("eqc proof OK: cosine_div (4 samples, fixed=False)");
}
