// GENERATED by eqc — self-asserting proof for `lambda_max_of_d`.
// exit 0 ⟺ the emitted f64 (and fixed-point) code matches the SymPy reference.
/// GENERATED by eqc from: lambda_max_of_d = 2*d
/// f64 variant — dynamics path (not bitwise-deterministic across targets on libm calls).
#[inline(always)]
pub fn lambda_max_of_d_f64(d: f64) -> f64 {
    2.0*d
}

/// GENERATED by eqc from: lambda_max_of_d = 2*d
/// Fixed-point Q32 variant — inputs/output are round(v * 2^32) as i64.
/// BITWISE-DETERMINISTIC on every target (pure integer arithmetic, i128 intermediates).
#[inline(always)]
pub fn lambda_max_of_d_fixed(d: i64) -> i64 {
    const SHIFT: u32 = 32;
    let _ = SHIFT; // documents the Q-format scale of inputs/output
    ((((8589934592i128) * (d as i128)) / 4294967296i128)) as i64
}

fn main() {
    let got = lambda_max_of_d_f64(3.0f64);
    assert!((got - (6.0f64)).abs() < 0.000000000001f64, "f64 sample 0: got {} want 6.0", got);
    let got_fx = lambda_max_of_d_fixed((12884901888i64)) as f64 / (4294967296u64 as f64);
    assert!((got_fx - (6.0f64)).abs() < 0.000000000001f64, "fixed sample 0: got {} want 6.0", got_fx);
    let got = lambda_max_of_d_f64(7.5f64);
    assert!((got - (15.0f64)).abs() < 0.000000000001f64, "f64 sample 1: got {} want 15.0", got);
    let got_fx = lambda_max_of_d_fixed((32212254720i64)) as f64 / (4294967296u64 as f64);
    assert!((got_fx - (15.0f64)).abs() < 0.000000000001f64, "fixed sample 1: got {} want 15.0", got_fx);
    let got = lambda_max_of_d_f64(1.0f64);
    assert!((got - (2.0f64)).abs() < 0.000000000001f64, "f64 sample 2: got {} want 2.0", got);
    let got_fx = lambda_max_of_d_fixed((4294967296i64)) as f64 / (4294967296u64 as f64);
    assert!((got_fx - (2.0f64)).abs() < 0.000000000001f64, "fixed sample 2: got {} want 2.0", got_fx);
    let got = lambda_max_of_d_f64(12.0f64);
    assert!((got - (24.0f64)).abs() < 0.000000000001f64, "f64 sample 3: got {} want 24.0", got);
    let got_fx = lambda_max_of_d_fixed((51539607552i64)) as f64 / (4294967296u64 as f64);
    assert!((got_fx - (24.0f64)).abs() < 0.000000000001f64, "fixed sample 3: got {} want 24.0", got_fx);
    println!("eqc proof OK: lambda_max_of_d (4 samples, fixed=True)");
}
