// rust-core/tests/eqc_proofs_test.rs
// CI-runnable verification that the hand-derived math in `src/lib.rs` matches its SymPy
// source of truth (generated by tools/eqc). Each included fn is the eqc-emitted Rust; the
// asserts encode the EXACT SymPy-evaluated reference values. Any future hand-edit that breaks
// the math fails this test — no prose, just a falsifiable assertion.
//
//   cargo test --test eqc_proofs_test
//
// Regenerate (don't hand-edit) with tools/eqc. NOTE: sympy's rust_code mis-distributes
// (Add)/Mul — feed eqc forms where the numerator is a single symbol (see cosine_div).
#[path = "../eqc-proofs/cheby_coeff_inner.fn.rs"]
mod cheby_coeff_inner_mod;
#[path = "../eqc-proofs/cheby_recur_weight.fn.rs"]
mod cheby_weight_mod;
#[path = "../eqc-proofs/cosine_div.fn.rs"]
mod cosine_div_mod;
#[path = "../eqc-proofs/lambda_max_of_d.fn.rs"]
mod lambda_max_mod;

use cheby_coeff_inner_mod::cheby_coeff_inner_f64;
use cheby_weight_mod::cheby_recur_weight_f64;
use cosine_div_mod::cosine_div_f64;
use lambda_max_mod::lambda_max_of_d_f64;

#[test]
fn cheby_coeff_inner_matches_sympy() {
    let cases: [(f64, f64, f64, f64, f64, f64, f64); 5] = [
        (2.0, 0.5, 1.0, 3.0, 0.7, 64.0, -0.006527974053609924),
        (4.0, 0.1, 0.3, 0.0, 1.2, 64.0, 0.028797192821449814),
        (1.0, 1.0, 2.0, 7.0, 2.5, 64.0, 0.005620869637645259),
        (3.0, 0.3, 0.8, 5.0, 0.2, 64.0, 0.008277731337292158),
        (2.5, 0.7, 1.5, 2.0, 2.9, 64.0, 0.026637531674752708),
    ];
    for (b, coeff, t, k, theta, qp, want) in cases {
        let got = cheby_coeff_inner_f64(b, coeff, t, k, theta, qp);
        assert!(
            (got - want).abs() < 1e-9,
            "cheby_coeff_inner got {got}, want {want}"
        );
    }
}

#[test]
fn lambda_max_matches_sympy() {
    for (d, want) in [(3.0, 6.0), (7.5, 15.0), (1.0, 2.0), (12.0, 24.0)] {
        let got = lambda_max_of_d_f64(d);
        assert!(
            (got - want).abs() < 1e-12,
            "lambda_max(2*{d}) got {got}, want {want}"
        );
    }
}

#[test]
fn cheby_recur_weight_matches_sympy() {
    for (b, want) in [
        (2.0, 1.0),
        (4.0, 0.5),
        (1.5, 1.3333333333333333),
        (8.0, 0.25),
    ] {
        let got = cheby_recur_weight_f64(b);
        assert!(
            (got - want).abs() < 1e-12,
            "cheby_recur_weight(2/{b}) got {got}, want {want}"
        );
    }
}

#[test]
fn cosine_div_matches_sympy() {
    // (dot, na, nb, want)
    let cases: [(f64, f64, f64, f64); 4] = [
        (0.0, 1.0, 1.0, 0.0),                      // orthogonal
        (25.0, 25.0, 25.0, 1.0),                   // parallel (3,4)x(3,4)
        (4.0, 5.0, 5.0, 0.8),                      // (1,2)x(2,1)
        (-10.0, 13.0, 52.0, -0.38461538461538464), // (2,-3)x(4,6)
    ];
    for (dot, na, nb, want) in cases {
        let got = cosine_div_f64(dot, na, nb);
        assert!(
            (got - want).abs() < 1e-12,
            "cosine_div({dot},{na},{nb}) got {got}, want {want}"
        );
    }
}
