// rust-core/tests/eqc_cheby_test.rs
// CI-runnable verification that the Chebyshev-coefficient formula in `spectral_propagate`
// (src/lib.rs) matches its SymPy source of truth. Uses the eqc-generated function directly so
// `cargo test` catches any future hand-edit that breaks the math — no prose, just a falsifiable assert.
//
//   cargo test --test eqc_cheby_test
//
// The function under test is GENERATED by tools/eqc — regenerate, don't hand-edit:
//   python3 tools/eqc/eqc.py --expr '2*exp(-0.5*b*coeff*t - 0.5*b*coeff*t*cos(theta))*cos(k*theta)/qp' \
//           --args b coeff t k theta qp
#[path = "../eqc-proofs/cheby_coeff_inner.fn.rs"]
mod cheby;
use cheby::cheby_coeff_inner_f64;

#[test]
fn cheby_coeff_inner_matches_sympy() {
    // Sample points; expected values are the exact SymPy evaluation (machine-precision),
    // captured by eqc's emit_proof_program. Any divergence (e.g. a bad refactor of the
    // coefficient loop) fails this test.
    let cases: [(f64, f64, f64, f64, f64, f64, f64); 5] = [
        (2.0, 0.5, 1.0, 3.0, 0.7, 64.0, -0.006527974053609924),
        (4.0, 0.1, 0.3, 0.0, 1.2, 64.0,  0.028797192821449814),
        (1.0, 1.0, 2.0, 7.0, 2.5, 64.0,  0.005620869637645259),
        (3.0, 0.3, 0.8, 5.0, 0.2, 64.0,  0.008277731337292158),
        (2.5, 0.7, 1.5, 2.0, 2.9, 64.0,  0.026637531674752708),
    ];
    for (b, coeff, t, k, theta, qp, want) in cases {
        let got = cheby_coeff_inner_f64(b, coeff, t, k, theta, qp);
        assert!(
            (got - want).abs() < 1e-9,
            "cheby_coeff_inner(b={b}, coeff={coeff}, t={t}, k={k}, theta={theta}) = {got}, want {want}"
        );
    }
}
